disabled_rules:
  - cyclomatic_complexity
  - duplicate_enum_cases
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - inclusive_language
  - large_tuple
  - trailing_whitespace
  - nesting
  - type_body_length
  - notification_center_detachment
  - non_optional_string_data_conversion
opt_in_rules:
  - attributes
  - balanced_xctest_lifecycle
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - direct_return
  - discarded_notification_center_observer
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - identical_operands
  - implicit_return
  - last_where
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - return_value_from_void_function
  - shorthand_optional_binding
  - sorted_first_last
  - strict_fileprivate
  - superfluous_else
  - switch_case_on_newline
  - test_case_accessibility
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - weak_delegate
  - yoda_condition
analyzer_rules:
  - unused_declaration
  - unused_import
included:
  - Guavapay3DS2DemoUI
  - Guavapay3DS2DemoUITests
excluded:
  - Package.swift
  - Guavapay3DS2
  - Guavapay3DS2Tests
  - DerivedData
  - .build
  - build
file_length:
    warning: 800
    error: 1000
line_length:
  ignores_urls: true
  ignores_comments: true
type_name:
  max_length:
    warning: 50
