#!/usr/bin/env bash
LC_ALL=C

possible_paths=("/opt/homebrew/bin" "/usr/local/bin")

find_command_path() {
    local command_name=$1
    for path in "${possible_paths[@]}"; do
        if [[ -x "${path}/${command_name}" ]]; then
            echo "${path}/${command_name}"
            return 0
        fi
    done
    return 1
}

SWIFT_LINT=$(find_command_path "swiftlint")
if [[ -z $SWIFT_LINT ]]; then
    echo "SwiftLint is not installed"
    exit 1
fi

SWIFT_FORMAT=$(find_command_path "swiftformat")
if [[ -z $SWIFT_FORMAT ]]; then
    echo "SwiftFormat is not installed"
    exit 1
fi

git diff --cached --name-only --diff-filter=ACMR | while read filename; do
  if [[ "${filename##*.}" == "swift" ]]; then
    ${SWIFT_FORMAT} --quiet "${filename}"
    git add "$filename"
    ${SWIFT_LINT} lint --quiet --strict "${filename}" || {
      echo "SwiftLint issues were found, fix them to be able to commit"
      exit 1
    }
  fi
done